### ISSUE TITLE
Question for adapting to textline recognition and variable-size images?

### ISSUE THREAD

**Issue by AndiezPham** [FangShancheng/ABINet#17]
Thanks for your amazing repo!
I have a textline dataset and I want to get a solution for using your work to adapt my dataset.
Can the system be used for variable-size images (Not fixed size - 32 x 128) and variable-size text length (according to a max text-length of mini-batch ,not using fixed dataset_max_length)? 
Could you refer to me a solution?
Thanks!

**Comment by FangShancheng** [comment]
Some points for adapting t textline recognition:

**Comment by FangShancheng** [comment]
Some points for adapting t textline recognition:
1. Dynamically set `image_height` and `image_width` in config according to image sizes.
2. Dynamically set `feature_height` and `feature_width` in `ResTranformer` and `PositionAttention`.
3. Also, extremely long text will cause low efficiency in vision feature sequence modeling (i.e, `ResTranformer`) due to the property of Transformer, which could be replaced by RNN or be removed directly.
4. Change `max_length` to a bigger value rather than 25 used in scene text recognition.
5. In all, basically you should only change some setting in the vision model.
